### ISSUE TITLE
Adding models issue -- Easy Diffusion v3.0.7

### ISSUE THREAD

**Issue by JamesonBeckwith** [easydiffusion/easydiffusion#1789]
Hi I cannot get models other then the default:sd-v1-5.safetensors to run. I am using:
Easy Diffusion v3.0.7
Linux Mint 21
Firefox v.125.0.2

I have tried adding 3 different models: 
sd_xl_base_1.0.safetensors
SSD-1B-A1111.safetensors
ProteusV0.2.safetensors

I downloaded these from Huggingface and added them directly to HOMEDIR/easy-diffusion/models/stable-diffusion. More then 1 added model causes Easy Diffusion to self terminate. Once I delete the extra models the server works again.
-------------------------------------------------------------
Two different error message on the server page are possible: 
1) Error: Could not load the stable-diffusion model! Reason: 1
2) Error: Stable Diffusion had an error. Please check the logs in the command-line window.
Error: Connection with server lost.
waitUntil@http://localhost:9000/media/js/engine.js:324:23
-------------------------------------------------------------
Error message in CLI: 
10:04:24.759 INFO cpu Session 1717077818759 starting task    task_manager.py:280
140136027761296 on AMD Ryzen 7 3800X 8-Core Processor                           
10:04:24.829 INFO cpu loading stable-diffusion model from         __init__.py:52
/home/beck/easy-diffusion/models/stable-diffusion/sd_xl_base_1.0.               
safetensors to device: cpu                                                      
10:04:26.209 INFO cpu loading on diffusers                       __init__.py:174
10:04:26.210 INFO cpu using config:                              __init__.py:176
/home/beck/easy-diffusion/installer_files/env/lib/python3.8/site                
-packages/sdkit/models/models_db/configs/sd-xl-base-1.0.yaml                    
10:04:26.225 INFO cpu using attn_precision: fp32                 __init__.py:192
10:04:27.151 ERROR AnyIO worker thread CUDA error:         device_manager.py:234
CUDA-capable device(s) is/are busy or unavailable                               
CUDA kernel errors might be asynchronously reported at                          
some other API call, so the stacktrace below might be                           
incorrect.                                                                      
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.                          
Compile with `TORCH_USE_CUDA_DSA` to enable device-side                         
assertions.                                                                     
                                                                                
10:04:27.343 ERROR AnyIO worker thread CUDA error:         device_manager.py:234
CUDA-capable device(s) is/are busy or unavailable                               
CUDA kernel errors might be asynchronously reported at                          
some other API call, so the stacktrace below might be                           
incorrect.                                                                      
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.                          
Compile with `TORCH_USE_CUDA_DSA` to enable device-side                         
assertions.                                                                     
                                                                                
Killed
Press any key to continue

**Comment by JamesonBeckwith** [comment]
I think the issue is fixed. It looks like I was using too much RAM. I restarted my computer and did not open certain applications. I can now run the other AI models.
