### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by Satyr23CH** [easydiffusion/easydiffusion#1971]
What is the problem? 

`Install dir: C:\EasyDiffusion\
C:\EasyDiffusion\installer_files\env\Library\bin\git.exe
C:\Program Files\Git\cmd\git.exe
git version 2.42.0.windows.1
C:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
C:\EasyDiffusion\installer_files\env\Scripts\conda.exe
conda 23.7.3
.
COMSPEC=C:\WINDOWS\system32\cmd.exe

Name                       AdapterRAM DriverDate                DriverVersion
----                       ---------- ----------                -------------
NVIDIA GeForce RTX 4060 Ti 4293918720 20250821000000.000000-000 32.0.15.8115

"Easy Diffusion - v3"

"Easy Diffusion's git repository was already installed. Updating from main.."
No local changes to save
HEAD is now at d37660c5 Merge pull request #1770 from Skoteinos1/patch-1
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
520 Datei(en) kopiert
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
Ein Unterverzeichnis oder eine Datei mit dem Namen "tmp" existiert bereits.
PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages
PYTHON=C:\EasyDiffusion\installer_files\env\python.exe
Python 3.8.5
Current torch version: (2, 0, 1) (2.0.1+cu117)
torchruntime: 1.23.0
torch: 2.0.1+cu117
torchvision: 0.15.2+cu117
sdkit: 2.0.15.17
stable-diffusion-sdkit: 2.1.5
diffusers: 0.21.4
{'backend': 'ed_diffusers',
 'filename_format': '$p_$tsb64',
 'folder_format': '$id',
 'model': {'stable-diffusion': 'cyberrealisticPony_v130'},
 'models_dir': 'C:\\AI\\Models\\',
 'net': {'listen_port': 9000, 'listen_to_network': False},
 'render_devices': ['cuda'],
 'ui': {'open_browser_on_start': True},
 'update_branch': 'main',
 'use_v3_engine': True,
 'vram_usage_level': 'balanced'}

Easy Diffusion installation complete, starting the server!

--- GPUs ---
0. GPU(vendor_id='10de', vendor_name='NVIDIA Corporation', device_id='2805', device_name='AD106 [GeForce RTX 4060 Ti 16GB]', is_discrete=True)

--- RECOMMENDED TORCH PLATFORM ---
cu124

--- CONFIGURATION ---
PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages
Python:  C:\EasyDiffusion\installer_files\env\python.EXE
Version: 3.8.5
Checking network settings
Set listen port to  9000

Launching uvicorn

01:56:25.273 INFO MainThread started in C:\EasyDiffusion\stable-diffusion                                   server.py:31
01:56:25.275 INFO MainThread started at 09/08/25 01:56:25                                                   server.py:32
stable-diffusion model(s) found.
gfpgan model(s) found.
realesrgan model(s) found.
vae model(s) found.
01:56:25.589 INFO MainThread Start new Rendering Thread on device: cuda                              task_manager.py:410
01:56:25.597 INFO cuda Device usage during initialization:                                                 runtime.py:35
01:56:25.597 INFO cuda CPU utilization: 4.5%, System RAM used: 8.7 of 63.8 GiB, GPU RAM used          memory_utils.py:58
(cuda:0): 1.1 of 16.0 GiB (peak: 0.0 GiB)
01:56:25.597 INFO cuda Setting cuda as active, with precision: half                                device_manager.py:123
01:56:25.605 ERROR cuda Error while loading stable-diffusion model:                                      __init__.py:100
C:\AI\Models\stable-diffusion\cyberrealisticPony_v130.safetensors
01:56:25.606 ERROR cuda 'NoneType' object has no attribute 'load_model'                                  __init__.py:106
Traceback (most recent call last):
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager\__init__.py", line 91, in load_default_models
    backend.load_model(
AttributeError: 'NoneType' object has no attribute 'load_model'
01:56:25.611 ERROR cuda Error while loading vae model: None                                              __init__.py:100
01:56:25.611 ERROR cuda 'NoneType' object has no attribute 'load_model'                                  __init__.py:106
Traceback (most recent call last):
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager\__init__.py", line 91, in load_default_models
    backend.load_model(
AttributeError: 'NoneType' object has no attribute 'load_model'
01:56:25.615 ERROR cuda Error while loading hypernetwork model: None                                     __init__.py:100
01:56:25.615 ERROR cuda 'NoneType' object has no attribute 'load_model'                                  __init__.py:106
Traceback (most recent call last):
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager\__init__.py", line 91, in load_default_models
    backend.load_model(
AttributeError: 'NoneType' object has no attribute 'load_model'
01:56:25.619 ERROR cuda Error while loading lora model: None                                             __init__.py:100
01:56:25.620 ERROR cuda 'NoneType' object has no attribute 'load_model'                                  __init__.py:106
Traceback (most recent call last):
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager\__init__.py", line 91, in load_default_models
    backend.load_model(
AttributeError: 'NoneType' object has no attribute 'load_model'
01:56:26.611 INFO MainThread Opening browser..                                                                app.py:317
╭────────────────────────────────────────────── Easy Diffusion is ready ───────────────────────────────────────────────╮
│                                                                                                                      │
│ Easy Diffusion is ready to serve requests.                                                                           │
│                                                                                                                      │
│ A new browser tab should have been opened by now.                                                                    │
│ If not, please open your web browser and navigate to http://localhost:9000/                                          │
│                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\EasyDiffusion\ui\easydiffusion\server.py", line 103, in read_web_data
    return read_web_data_internal(key, scan_for_malicious=scan_for_malicious)
  File "C:\EasyDiffusion\ui\easydiffusion\server.py", line 236, in read_web_data_internal
    return JSONResponse(model_manager.getModels(scan_for_malicious), headers=NOCACHE_HEADERS)
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager\__init__.py", line 397, in getModels
    backend.refresh_models()
AttributeError: 'NoneType' object has no attribute 'refresh_models'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\EasyDiffusion\ui\easydiffusion\server.py", line 103, in read_web_data
    return read_web_data_internal(key, scan_for_malicious=scan_for_malicious)
  File "C:\EasyDiffusion\ui\easydiffusion\server.py", line 236, in read_web_data_internal
    return JSONResponse(model_manager.getModels(scan_for_malicious), headers=NOCACHE_HEADERS)
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager\__init__.py", line 397, in getModels
    backend.refresh_models()
AttributeError: 'NoneType' object has no attribute 'refresh_models'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\EasyDiffusion\ui\easydiffusion\server.py", line 103, in read_web_data
    return read_web_data_internal(key, scan_for_malicious=scan_for_malicious)
  File "C:\EasyDiffusion\ui\easydiffusion\server.py", line 236, in read_web_data_internal
    return JSONResponse(model_manager.getModels(scan_for_malicious), headers=NOCACHE_HEADERS)
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager\__init__.py", line 397, in getModels
    backend.refresh_models()
AttributeError: 'NoneType' object has no attribute 'refresh_models'
`

**Comment by WestonGFX** [comment]
### My Forge beta 3.5 engine version of Easy Diffusion did not work either **(at first)**.

_I fixed it by re-running it again after installing it the first time._
----------
I have an RTX 5080. Just built a new PC so I recently installed Windows 11 and Easy Diffusion.

Can post my command prompt code output below when launching the new Forge backend after previously being on 3.0 instead of 3.5 so it is isntalling. The web UI does launch but when I add a new task the status in the top right remains orange `rgb(200, 139, 0)` " Stable Diffusion is loading.." and does not go green to indicate that it is "working" on the task. But then I exited the program, and restarted it. Make sure your GPU has the right version of CUDA for Forge and that Forge is using the right versions of Python/Pytorch/CUDA. I just had to ask ChatGPT by pasting all of my command prompt code and saying it was hanging when trying to render images but the web UI loaded fine, and it told me how to confirm that I had the right CUDA version installed.

Close Easy Diffusion completely. Kill any lingering python.exe processes if needed.

1. Sanity-check that Forge can see the 5080 by itself.

Open a terminal in:
```
C:\EasyDiffusion\webui\system\
```
Run:
```
.\python.exe -c "import torch; print('CUDA?', torch.cuda.is_available(), 'CUDAver', torch.version.cuda, 'GPU', torch.cuda.get_device_name(0))"
```

You should see CUDA? True and CUDAver 12.8 plus your device name.

If this prints False or errors: reinstall cu128 in the Forge env:
```
.\python.exe -s -m pip install --upgrade torch torchvision --index-url https://download.pytorch.org/whl/cu128
```
This is exactly what Puget recommends for Blackwell compatibility

### Now it works! 

**Just close and restart! Hope that works for you.**

</br>

_Here was my command prompt output after running Forge (v3.5) on the beta channel for the first time (so it needed to run the install commands first before the web ui would pop up. But then it did not work. So I just had to close it and re-run Easy Diffusion._ 

**Code from command prompt:**

```
Install dir: C:\EasyDiffusion\
C:\EasyDiffusion\installer_files\env\Library\bin\git.exe
git version 2.48.1.windows.1
C:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
C:\EasyDiffusion\installer_files\env\Scripts\conda.exe
conda 25.1.1
.
COMSPEC=C:\WINDOWS\system32\cmd.exe

Name                    AdapterRAM DriverDate                DriverVersion
----                    ---------- ----------                -------------
NVIDIA GeForce RTX 5080 4293918720 20250821000000.000000-000 32.0.15.8115



"Easy Diffusion - v3"

"Easy Diffusion's git repository was already installed. Updating from beta.."
No local changes to save
HEAD is now at 8bbdc1e0 Handle empty backend_config values
Already on 'beta'
Your branch is up to date with 'origin/beta'.
Already up to date.
533 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file tmp already exists.
The system cannot find the file specified.
The system cannot find the file specified.
PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages
PYTHON=C:\EasyDiffusion\installer_files\env\python.exe
Python 3.9.21
Current torch version: (2, 8, 0) (2.8.0+cu128)
> "C:\EasyDiffusion\installer_files\env\python.exe" -m pip install --upgrade setuptools==59.8.0
Collecting setuptools==59.8.0
  Using cached setuptools-59.8.0-py3-none-any.whl.metadata (5.0 kB)
Using cached setuptools-59.8.0-py3-none-any.whl (952 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 69.5.1
    Uninstalling setuptools-69.5.1:
      Successfully uninstalled setuptools-69.5.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda 25.1.1 requires setuptools>=60.0.0, but you have setuptools 59.8.0 which is incompatible.
sdkit 2.1.0 requires setuptools==69.5.1, but you have setuptools 59.8.0 which is incompatible.
Successfully installed setuptools-59.8.0
torchruntime: 1.23.1
torch: 2.8.0+cu128
torchvision: 0.23.0+cu128
sdkit: 2.1.0
stable-diffusion-sdkit: 2.1.5
diffusers: 0.28.2
{'backend': 'webui',
 'models_dir': 'C:\\EasyDiffusion\\models',
 'net': {'listen_port': 1337, 'listen_to_network': True},
 'render_devices': ['cuda'],
 'ui': {'open_browser_on_start': True},
 'update_branch': 'beta',
 'use_v3_engine': False,
 'vram_usage_level': 'balanced'}


Easy Diffusion installation complete, starting the server!


--- GPUs ---
0. GPU(vendor_id='10de', vendor_name='NVIDIA Corporation', device_id='2c02', device_name='GB203 [GeForce RTX 5080]', is_discrete=True)

--- RECOMMENDED TORCH PLATFORM ---
cu128

--- CONFIGURATION ---
PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages
Python:  C:\EasyDiffusion\installer_files\env\python.EXE
Version: 3.9.21
Checking network settings
Set listen port to  1337
Set bind_ip to  0.0.0.0

Launching uvicorn

08:14:34.934 INFO MainThread started in C:\EasyDiffusion\stable-diffusion                                   server.py:33
08:14:34.936 INFO MainThread started at 09/09/25 08:14:34                                                   server.py:34
C:\EasyDiffusion\installer_files\env\lib\site-packages\pydantic\_internal\_config.py:345: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
08:14:35.183 INFO MainThread Loading backend: webui                                                backend_manager.py:99
conda:  C:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
conda:  C:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
08:14:35.261 INFO MainThread Loaded backend: <module 'webui' from                                  backend_manager.py:69
'C:\\EasyDiffusion\\ui\\easydiffusion\\backends\\webui\\__init__.py'>
08:14:35.265 INFO MainThread Expected WebUI backend dir: C:\EasyDiffusion\webui                          __init__.py:117
Installing the WebUI backend..
C:\EasyDiffusion\installer_files\env\lib\site-packages\conda\base\context.py:202: FutureWarning: Adding 'defaults' to channel list implicitly is deprecated and will be removed in 25.3.

To remove this warning, please choose a default channel explicitly with conda's regular configuration system, e.g. by adding 'defaults' to the list of channels:

  conda config --add channels defaults

For more information see https://docs.conda.io/projects/conda/en/stable/user-guide/configuration/use-condarc.html

  deprecated.topic(
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\EasyDiffusion\webui\system




Downloading and Extracting Packages: ...working... done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate C:\EasyDiffusion\webui\system
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Installing packages..
C:\EasyDiffusion\installer_files\env\lib\site-packages\conda\base\context.py:202: FutureWarning: Adding 'defaults' to channel list implicitly is deprecated and will be removed in 25.3.

To remove this warning, please choose a default channel explicitly with conda's regular configuration system, e.g. by adding 'defaults' to the list of channels:

  conda config --add channels defaults

For more information see https://docs.conda.io/projects/conda/en/stable/user-guide/configuration/use-condarc.html

  deprecated.topic(
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
    current version: 25.1.1
    latest version: 25.7.0

Please update conda by running

    $ conda update -n base -c conda-forge conda



## Package Plan ##

  environment location: C:\EasyDiffusion\webui\system

  added / updated specs:
    - git
    - python=3.10


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.8                |       h2466b09_7          54 KB  conda-forge
    ca-certificates-2025.8.3   |       h4c7d964_0         151 KB  conda-forge
    git-2.51.0                 |       h57928b3_1       117.4 MB  conda-forge
    libexpat-2.7.1             |       hac47afa_0         138 KB  conda-forge
    libffi-3.4.6               |       h537db12_1          44 KB  conda-forge
    liblzma-5.8.1              |       h2466b09_2         102 KB  conda-forge
    libsqlite-3.50.4           |       hf5d6505_0         1.2 MB  conda-forge
    libzlib-1.3.1              |       h2466b09_2          54 KB  conda-forge
    openssl-3.5.2              |       h725018a_0         8.8 MB  conda-forge
    pip-25.2                   |     pyh8b19718_0         1.1 MB  conda-forge
    python-3.10.18             |h8c5b53a_0_cpython        15.1 MB  conda-forge
    setuptools-80.9.0          |     pyhff2d567_0         731 KB  conda-forge
    tk-8.6.13                  |       h2c6b04d_2         3.3 MB  conda-forge
    tzdata-2025b               |       h78e105d_0         120 KB  conda-forge
    ucrt-10.0.26100.0          |       h57928b3_0         678 KB  conda-forge
    vc-14.3                    |      h41ae7f8_31          18 KB  conda-forge
    vc14_runtime-14.44.35208   |      h818238b_31         666 KB  conda-forge
    vcomp14-14.44.35208        |      h818238b_31         111 KB  conda-forge
    wheel-0.45.1               |     pyhd8ed1ab_1          61 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       149.9 MB

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/win-64::bzip2-1.0.8-h2466b09_7
  ca-certificates    conda-forge/noarch::ca-certificates-2025.8.3-h4c7d964_0
  git                conda-forge/win-64::git-2.51.0-h57928b3_1
  libexpat           conda-forge/win-64::libexpat-2.7.1-hac47afa_0
  libffi             conda-forge/win-64::libffi-3.4.6-h537db12_1
  liblzma            conda-forge/win-64::liblzma-5.8.1-h2466b09_2
  libsqlite          conda-forge/win-64::libsqlite-3.50.4-hf5d6505_0
  libzlib            conda-forge/win-64::libzlib-1.3.1-h2466b09_2
  openssl            conda-forge/win-64::openssl-3.5.2-h725018a_0
  pip                conda-forge/noarch::pip-25.2-pyh8b19718_0
  python             conda-forge/win-64::python-3.10.18-h8c5b53a_0_cpython
  setuptools         conda-forge/noarch::setuptools-80.9.0-pyhff2d567_0
  tk                 conda-forge/win-64::tk-8.6.13-h2c6b04d_2
  tzdata             conda-forge/noarch::tzdata-2025b-h78e105d_0
  ucrt               conda-forge/win-64::ucrt-10.0.26100.0-h57928b3_0
  vc                 conda-forge/win-64::vc-14.3-h41ae7f8_31
  vc14_runtime       conda-forge/win-64::vc14_runtime-14.44.35208-h818238b_31
  vcomp14            conda-forge/win-64::vcomp14-14.44.35208-h818238b_31
  wheel              conda-forge/noarch::wheel-0.45.1-pyhd8ed1ab_1



                                                      done
Preparing transaction: done
Verifying transaction: done
Executing transaction: - Insufficient permissions to write menu folder.  Falling back to user location

done
git version 2.51.0.windows.1
Python 3.10.18
Cloning into 'C:\EasyDiffusion\webui\webui'...
Collecting torchruntime
  Using cached torchruntime-1.23.1-py3-none-any.whl.metadata (14 kB)
Using cached torchruntime-1.23.1-py3-none-any.whl (62 kB)
Installing collected packages: torchruntime
Successfully installed torchruntime-1.23.1
Looking in indexes: https://download.pytorch.org/whl/cu128
Collecting torch
  Downloading https://download.pytorch.org/whl/cu128/torch-2.8.0%2Bcu128-cp310-cp310-win_amd64.whl.metadata (29 kB)
Collecting torchvision
  Downloading https://download.pytorch.org/whl/cu128/torchvision-0.23.0%2Bcu128-cp310-cp310-win_amd64.whl.metadata (6.3 kB)
Collecting filelock (from torch)
  Downloading https://download.pytorch.org/whl/filelock-3.13.1-py3-none-any.whl.metadata (2.8 kB)
Collecting typing-extensions>=4.10.0 (from torch)
  Downloading https://download.pytorch.org/whl/typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy>=1.13.3 (from torch)
  Using cached https://download.pytorch.org/whl/sympy-1.13.3-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch)
  Downloading https://download.pytorch.org/whl/networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
Collecting jinja2 (from torch)
  Downloading https://download.pytorch.org/whl/Jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting fsspec (from torch)
  Downloading https://download.pytorch.org/whl/fsspec-2024.6.1-py3-none-any.whl.metadata (11 kB)
Collecting numpy (from torchvision)
  Downloading https://download.pytorch.org/whl/numpy-2.1.2-cp310-cp310-win_amd64.whl.metadata (59 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision)
  Downloading https://download.pytorch.org/whl/pillow-11.0.0-cp310-cp310-win_amd64.whl.metadata (9.3 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch)
  Downloading https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
     ---------------------------------------- 536.2/536.2 kB 1.0 MB/s  0:00:00
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Downloading https://download.pytorch.org/whl/MarkupSafe-2.1.5-cp310-cp310-win_amd64.whl (17 kB)
Downloading https://download.pytorch.org/whl/cu128/torch-2.8.0%2Bcu128-cp310-cp310-win_amd64.whl (3461.4 MB)
   ---------------------------------------- 3.5/3.5 GB 8.0 MB/s  0:05:47
Downloading https://download.pytorch.org/whl/cu128/torchvision-0.23.0%2Bcu128-cp310-cp310-win_amd64.whl (7.5 MB)
   ---------------------------------------- 7.5/7.5 MB 11.4 MB/s  0:00:00
Downloading https://download.pytorch.org/whl/pillow-11.0.0-cp310-cp310-win_amd64.whl (2.6 MB)
   ---------------------------------------- 2.6/2.6 MB 8.2 MB/s  0:00:00
Using cached https://download.pytorch.org/whl/sympy-1.13.3-py3-none-any.whl (6.2 MB)
Downloading https://download.pytorch.org/whl/typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading https://download.pytorch.org/whl/filelock-3.13.1-py3-none-any.whl (11 kB)
Downloading https://download.pytorch.org/whl/fsspec-2024.6.1-py3-none-any.whl (177 kB)
Downloading https://download.pytorch.org/whl/Jinja2-3.1.4-py3-none-any.whl (133 kB)
Downloading https://download.pytorch.org/whl/networkx-3.3-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 1.7/1.7 MB 6.6 MB/s  0:00:00
Downloading https://download.pytorch.org/whl/numpy-2.1.2-cp310-cp310-win_amd64.whl (12.9 MB)
   ---------------------------------------- 12.9/12.9 MB 7.1 MB/s  0:00:01
Installing collected packages: mpmath, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, fsspec, filelock, jinja2, torch, torchvision

Successfully installed MarkupSafe-2.1.5 filelock-3.13.1 fsspec-2024.6.1 jinja2-3.1.4 mpmath-1.3.0 networkx-3.3 numpy-2.1.2 pillow-11.0.0 sympy-1.13.3 torch-2.8.0+cu128 torchvision-0.23.0+cu128 typing-extensions-4.12.2
>  ['C:\\EasyDiffusion\\webui\\system\\python.exe', '-m', 'pip', 'install', 'torch', 'torchvision', '--index-url', 'https://download.pytorch.org/whl/cu128']
No local changes to save
HEAD is now at dfdcbab6 Fix SD upscale Batch count (#2950)
HEAD is now at dfdcbab6 Fix SD upscale Batch count (#2950)
08:22:47.449 INFO MainThread Applying WebUI patch:                                                       __init__.py:137
C:\EasyDiffusion\ui\easydiffusion\backends\webui\forge_exception_leak_patch.patch
08:22:48.132 INFO MainThread Applying WebUI patch:                                                       __init__.py:137
C:\EasyDiffusion\ui\easydiffusion\backends\webui\forge_model_crash_recovery.patch
08:22:48.813 INFO MainThread Applying WebUI patch:                                                       __init__.py:137
C:\EasyDiffusion\ui\easydiffusion\backends\webui\forge_api_refresh_text_encoders.patch
08:22:49.478 INFO MainThread Applying WebUI patch:                                                       __init__.py:137
C:\EasyDiffusion\ui\easydiffusion\backends\webui\forge_loader_force_gc.patch
08:22:50.134 INFO MainThread Applying WebUI patch:                                                       __init__.py:137
C:\EasyDiffusion\ui\easydiffusion\backends\webui\forge_monitor_parent_process.patch
08:22:50.772 INFO MainThread Applying WebUI patch:                                                       __init__.py:137
C:\EasyDiffusion\ui\easydiffusion\backends\webui\forge_disable_corrupted_model_renaming.patch
08:22:54.610 INFO Thread-22 starting: webui.bat in C:\EasyDiffusion\webui\webui                          __init__.py:191
08:22:54.614 INFO Thread-22 COMMANDLINE_ARGS: --api --models-dir "C:\EasyDiffusion\models" --ckpt-dir    __init__.py:192
"C:\EasyDiffusion\models\stable-diffusion" --vae-dir "C:\EasyDiffusion\models\vae" --hypernetwork-dir
"C:\EasyDiffusion\models\hypernetwork" --gfpgan-models-path "C:\EasyDiffusion\models\gfpgan"
--realesrgan-models-path "C:\EasyDiffusion\models\realesrgan" --lora-dir "C:\EasyDiffusion\models\lora"
--codeformer-models-path "C:\EasyDiffusion\models\codeformer" --embeddings-dir
"C:\EasyDiffusion\models\embeddings" --controlnet-dir "C:\EasyDiffusion\models\controlnet"
--text-encoder-dir "C:\EasyDiffusion\models\text-encoder" --skip-torch-cuda-test --disable-gpu-warning
--port 7860 --parent-pid 35896
stable-diffusion model(s) found.
gfpgan model(s) found.
realesrgan model(s) found.
vae model(s) found.
08:22:54.787 INFO MainThread Start new Rendering Thread on device: cuda                              task_manager.py:420
08:22:54.790 INFO cuda Setting cuda as active, with precision: half                                device_manager.py:123
08:22:56.794 INFO MainThread Opening browser..                                                                app.py:332
╭────────────────────────────────────────────── Easy Diffusion is ready ───────────────────────────────────────────────╮
│                                                                                                                      │
│ Easy Diffusion is ready to serve requests.                                                                           │
│                                                                                                                      │
│ A new browser tab should have been opened by now.                                                                    │
│ If not, please open your web browser and navigate to http://localhost:1337/                                          │
│                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
08:22:57.485 INFO AnyIO worker thread Scanning all model folders for models...                           __init__.py:501
08:22:58.151 INFO AnyIO worker thread Scanned 48 models. Nothing infected                                __init__.py:507
[WebUI] Cloning into 'C:\EasyDiffusion\webui\webui\repositories\stable-diffusion-webui-assets'...
[WebUI] Cloning into 'C:\EasyDiffusion\webui\webui\repositories\huggingface_guess'...
[WebUI] Cloning into 'C:\EasyDiffusion\webui\webui\repositories\BLIP'...
```

And here is my console output taken from Chrome Dev Tools:

```
08:22:57.340 utils.js:963 Persisted storage granted: false
08:22:57.385 (index):1 Unchecked runtime.lastError: The message port closed before a response was received.
08:22:57.386 inject.js:22 pageshow:  PageTransitionEvent
08:22:57.392 (index):1 Unchecked runtime.lastError: The message port closed before a response was received.
08:22:57.392 engine.js:1215 get models response Object
08:22:57.417 parameters.js:548 get config status response Object
08:22:57.420 plugins.js:64 loading script /plugins/core/Autoscroll.plugin.js
08:22:57.420 plugins.js:64 loading script /plugins/core/custom-modifiers.plugin.js
08:22:57.420 plugins.js:64 loading script /plugins/core/image-editor-improvements.plugin.js
08:22:57.420 plugins.js:64 loading script /plugins/core/lora-prompt-parser.plugin.js
08:22:57.420 plugins.js:64 loading script /plugins/core/model-tools.plugin.js
08:22:57.420 plugins.js:64 loading script /plugins/core/Modifiers-dnd.plugin.js
08:22:57.420 plugins.js:64 loading script /plugins/core/modifiers-toggle.plugin.js
08:22:57.420 plugins.js:64 loading script /plugins/core/Modifiers-wheel.plugin.js
08:22:57.420 plugins.js:64 loading script /plugins/core/release-notes.plugin.js
08:22:57.421 plugins.js:64 loading script /plugins/core/snow.plugin.js
08:22:57.421 plugins.js:64 loading script /plugins/core/tiled-image-download.plugin.js
08:22:57.481 engine.js:292 Unexpected server status. Server could be unavailable... Status: Unavailable
isServerAvailable @ engine.js:292
08:22:58.153 engine.js:1215 get models response Object
08:24:50.639 dnd.js:785 Content in drop zone
08:24:50.639 dnd.js:785 Content in drop zone
08:24:50.639 dnd.js:785 Content in drop zone
08:24:50.641 dnd.js:785 Content in drop zone
08:24:50.642 dnd.js:785 Content in drop zone
08:24:50.645 dnd.js:785 Content in drop zone
08:24:50.646 dnd.js:785 Content in drop zone
08:24:50.650 dnd.js:785 Content in drop zone
08:24:50.654 dnd.js:785 Content in drop zone
08:24:50.654 dnd.js:785 Content in drop zone
08:24:50.658 dnd.js:785 Content in drop zone
08:24:50.659 dnd.js:785 Content in drop zone
08:24:50.660 dnd.js:785 Content in drop zone
08:24:50.662 dnd.js:785 Content in drop zone
08:24:50.665 dnd.js:785 Content in drop zone
08:24:50.666 dnd.js:785 Content in drop zone
08:24:50.667 dnd.js:785 Content in drop zone
08:24:50.670 dnd.js:785 Content in drop zone
08:24:50.671 dnd.js:785 Content in drop zone
08:24:50.672 dnd.js:785 Content in drop zone
08:24:50.674 dnd.js:785 Content in drop zone
08:24:50.676 dnd.js:785 Content in drop zone
08:24:50.680 dnd.js:785 Content in drop zone
08:24:50.680 dnd.js:785 Content in drop zone
08:24:50.683 dnd.js:757 Content dropped...
08:25:09.291 :1337/bucket/default/embeddings/:1  Failed to load resource: the server responded with a status of 404 (Not Found)
08:25:09.301 :1337/bucket/default/lora/:1  Failed to load resource: the server responded with a status of 404 (Not Found)
08:26:58.518 engine.js:893 delay between clicking and making the server request: 370.69999999925494 ms
08:27:43.590 engine.js:986 Server Object render request Object was stopped
08:27:43.590 engine.js:893 delay between clicking and making the server request: 370.69999999925494 ms
08:28:37.679 engine.js:986 Server Object render request Object was stopped
08:28:37.679 engine.js:893 delay between clicking and making the server request: 370.69999999925494 ms
08:34:08.076 engine.js:986 Server Object render request Object was stopped
08:34:08.077 engine.js:893 delay between clicking and making the server request: 370.69999999925494 ms
08:34:54.564 main.js:2567 Cloudflare tunnel start result: Object
08:35:03.752 engine.js:986 Server Object render request Object was stopped
08:35:03.752 engine.js:893 delay between clicking and making the server request: 370.69999999925494 ms
08:35:38.303 engine.js:986 Server Object render request Object was stopped
08:35:38.304 engine.js:893 delay between clicking and making the server request: 370.69999999925494 ms
08:48:42.674 Fetch finished loading: GET "<URL>".
08:48:42.674 Fetch finished loading: GET "<URL>".
08:48:42.674 Fetch finished loading: GET "<URL>".
08:48:42.674 Fetch finished loading: GET "<URL>".
08:48:42.674 Fetch finished loading: GET "<URL>".
08:48:42.674 Fetch finished loading: GET "<URL>".
```
